content_retrieval:
  description: >
    Search the internet for content around '{subject}'.
    The content you retrieve will be used for generating Instagram Posts.
    The content you retrieve must come from trustworth sources.
    Keep track of where each content you retrieved came from, so that it can be inspected later on.
    Avoid old content, so to avoid outdated knowledge.
    Search and retrieve content from at least 3 sources.
  expected_output: >
    A summary of the searched content with the most important knowledge around '{subject}'.
    This summary should also include the sources of the content, like for example links and authors.

post_writting:
  description: >
    Create an Instagram Post using the summary provided to you around '{subject}' by the Content Retriever Agent.    
    The post should contain between 3 and 5 slides, each one explaning a bit around the subject.
    Approach the most important information around the subject.
    Make the text compelling and easy to understand by any sort of audience, technical and non-technical people.
    Include the sources you ended up using so for traceability and auditing.
    Do not make up any knowledge, use the content you were given to generate the post.
    Avoid using the exact same words from the content you were given, interpret the knowledge and put it in other words WHEN POSSIBLE.
  expected_output: >
    A markdown formatted text containing the Instagram post around '{subject}'.
    Each slide fo the post should be well defined on the text, separated by titles for example, alongside the sources of knowledge used on each slide.
    Suggestions of images for each slide are welcome, so we can search/create the images to use as backgrounds on each slide.